name: Run pytest with Conda

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9   # Replace with your desired Python version

      - name: Create Conda environment
        run: |
          conda env create -f environment.yml
          conda activate myutils-env
      
      - name: Install additional packages
        run: |
          pip install git+https://gitlab.com/ase/ase.git
          conda install -c conda-forge pymol-open-source
          pip install git+https://github.com/hits-mbm-dev/pepgen.git

      - name: Run pytest
        run: pytest   # Replace with the command to run your tests
